- name: "Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags:
    - skip
    - homebrew

- name: "Brew tap casks"
  # loops through the list and tap to casks
  community.general.homebrew_tap:
    name: "{{ item }}"
  with_items:
    - homebrew/cask-fonts
    - koekeishiya/formulae
    - ngrok/ngrok
    - FelixKratz/formulae
    - espanso/espanso
  tags:
    - install
    - homebrew

- name: "Install casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - font-jetbrains-mono-nerd-font
    # - font-hack-nerd-font
    # - font-fira-code-nerd-font
    - ngrok
    - maccy
    - alacritty
    - karabiner-elements
    - gimp
  tags:
    - install
    - homebrew

- name: "Install formulae"
  community.general.homebrew:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - commitizen
    - espanso
    - eza
    - fnm
    - fzf
    - gh
    - git
    - imagemagick
    - jq
    - lazygit
    - less
    - neovim
    - ripgrep
    - sketchybar
    - skhd
    - starship
    - stow
    - tldr
    - tmux
    - tree
    - yabai
    - yq
    - z
    - zsh
    - zsh-autosuggestions
    - zsh-history-substring-search
    - zsh-syntax-highlighting
  tags:
    - install
    - homebrew
